In [1]:
import numpy as np
import cv2

In [2]:
# best fiber extraction: Threshold Binary70 + Guassian Otsu's Thresholding
# best centre line: Threshold Binary70inv + closing + skel + remove small 1 contours

In [3]:
# 用来生成中心线的function
# 源代码来源 http://opencvpython.blogspot.com/2012/05/skeletonization-using-opencv-python.html
def Skeletonization(img):
    size = np.size(img)
    skel = np.zeros(img.shape,np.uint8)
    element = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3))
    done = False

    while( not done):
        eroded = cv2.erode(img,element)
        temp = cv2.dilate(eroded,element)
        temp = cv2.subtract(img,temp)
        skel = cv2.bitwise_or(skel,temp)
        img = eroded.copy()

        zeros = size - cv2.countNonZero(img)
        if zeros==size:
            done = True

    return skel

In [4]:
# 移除只有一个pixel的噪音
def remove_1_noise(pic):
    contours, hierarchy = cv2.findContours(pic, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    threshold_blobs_area = 0

    for i in range(1, len(contours)):
        index_level = int(hierarchy[0][i][1])
        if index_level <= i:
            cnt = contours[i]
            area = cv2.contourArea(cnt)
            if area <= threshold_blobs_area:
                cv2.drawContours(pic, [cnt], -1, 0, -1, 1)
    return pic

In [5]:
# 输入：原始图片 输出：fiber threshold和中心线
def extract_cline_fiber(pic):
    # 提取fiber部分
    ret,thresh1 = cv2.threshold(pic, 210, 255, cv2.THRESH_BINARY_INV)
    blur = cv2.GaussianBlur(thresh1, (5,5), 0)#blur的size可以修改
    _, th3 = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
#     cv2.imwrite("Guassian Otsu's Thresholding.bmp", th3) 
    
    # 提取centre line部分
    kernel = np.ones((5,5), np.uint8)
    ret,thresh1 = cv2.threshold(pic, 210, 255, cv2.THRESH_BINARY_INV)
    closing = cv2.morphologyEx(thresh1, cv2.MORPH_CLOSE, kernel)
    skel = Skeletonization(closing)
    skel = remove_1_noise(skel)
    
    return th3, skel

In [6]:
# 一键提取center line和fiber的图
pic = cv2.imread('220704.bmp',0)
th3, skel = extract_cline_fiber(pic)
cv2.imwrite('220704fibre.bmp', th3)
cv2.imwrite('220704cline.bmp', skel)

True

In [7]:
# 根据evaluate的曲线位置和evaluate的range生成取样区域
def eva_area(img, num=1, loc=1, thick=1):
    center = 130+300*(num-1)
    pic = np.zeros([630, 1160])
    if loc == 1:
        R = 25
    elif loc == 2:
        R = 50
    elif loc == 3:
        R = 100
    else:
        print('Please choose location 1, 2 or 3.')
        
    cv2.circle(pic, (center,130), R, 255, thick)
    cv2.rectangle(pic, (center-R-thick,130), (center+R+thick,130+R+thick), 0, -1)
    cv2.line(pic, (center-R,130), (center-R,130+470), 255, thick) 
    cv2.line(pic, (center+R,130), (center+R,130+470), 255, thick) 
    
    if img.shape[1]/img.shape[0] != 116/63:
        print('Image shape is not defult:', img.shape)
    pic = np.round(cv2.resize(pic, (img.shape[1],img.shape[0]))/255.)*255
    
    return pic

In [8]:
# 这里要搞一个根据框截图图片的function 从image变成croped

In [9]:
def get_contour_areas(contours):
    # returns the areas of all contours as list
    all_areas = []
    for cnt in contours:
        area = cv2.contourArea(cnt)
        all_areas.append(area)
    return all_areas

In [36]:
# 对提取的截取好的（一定和GT重合的）fiber图片进行contour分每个trajectory
def get_trajectory(croped):
    edged = cv2.Canny(np.uint8(croped), 50, 200)
    contours, hierarchy = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    sorted_contours = sorted(contours, key=cv2.contourArea, reverse=True)
    areas = get_contour_areas(sorted_contours)
    blk_image = np.zeros(croped.shape)
    if len(areas) > 12:
        idx = 12-len(areas)
        if np.any(np.array(areas[idx:]) > 100):
            print('Disconnetion may exist, please check!')
        else:
            n = 0
            for c in sorted_contours:
#                 print(c)
                cv2.drawContours(blk_image, c, -1, 170, cv2.FILLED)
#                 cv2.drawContours(blk_image, c, 0, 170, cv2.FILLED)
#                 cv2.waitKey(0)
                cv2.imwrite('contour_' + str(n) + '.png', blk_image)
                n+=1
    elif len(areas) < 12:
        print('Only %d trajectory detected, please check!' %len(areas))
    print (get_contour_areas(sorted_contours))
    print ("Number of contours found = ", len(contours))

In [37]:
get_trajectory(croped)

[8682.5, 8337.5, 8050.0, 7719.0, 7100.0, 6788.5, 6785.0, 6679.5, 6666.5, 6543.5, 6455.5, 5211.5, 13.0, 10.0, 4.0]
Number of contours found =  15


In [ ]:
# 根据生成的标准图片eva_area和输入图片计算该选中的area下的

In [15]:
o1 = eva_area(croped,num=1, loc=3, thick=10).astype(int)
np.unique(o1)
cv2.imwrite('o1.bmp', o1)

True

In [16]:
# 这里是随便截取一下打印提取的图片 看能不能用来跟上面的eva area重合一下
# height, w = th3.shape
l,u = 100, 450
h = 1000
w = int(h/63*116)
croped = th3[u:u+h, l:l+w]
croped = cv2.resize(croped, (1160, 630)).astype(int)
print(croped)
print(o1)
cv2.imwrite('croped.bmp', croped)
added_image = cv2.addWeighted(croped,0.4,o1,0.3,0)
cv2.imwrite('overlay.bmp', added_image)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


True

In [18]:
th3.shape

(1536, 2048)

In [46]:
image = cv2.imread('d3d10597-e629-4f08-853b-75472ae0de06.bmp',0)
kernel = np.ones((5,5), np.uint8)
ret,thresh1 = cv2.threshold(image, 70, 255, cv2.THRESH_BINARY_INV)
# Closing - for removing noise
# blur = cv2.GaussianBlur(image, (5,5), 0)
# _, th3 = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
closing = cv2.morphologyEx(thresh1, cv2.MORPH_CLOSE, kernel)
cv2.imwrite('Closing.bmp', closing)

skel = Skeletonization(closing)
cv2.imwrite('Closingskel.bmp', skel)

contours, hierarchy = cv2.findContours(skel, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
threshold_blobs_area = 0

for i in range(1, len(contours)):
    index_level = int(hierarchy[0][i][1])
    if index_level <= i:
        cnt = contours[i]
        area = cv2.contourArea(cnt)
        print(area)
        if area <= threshold_blobs_area:
            cv2.drawContours(skel, [cnt], -1, 0, -1, 1)
cv2.imwrite('removednoiseClosingskel.bmp', skel)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
15.5
1.5
0.0
0.0
0.0
0.0
0.0
0.0
0.5
0.0
0.0
3.0
8.5
14.5
0.0
8.5
0.0
0.0
0.0
0.0
0.0
0.0
5.0
5.0
0.0
10.5
0.0
0.0
0.0
0.0
0.0
0.0
0.5
0.0
0.0
0.0
33.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
46.0
0.0
11.5
11.0
0.0
24.0
35.5
0.0
16.0
40.0
0.0
0.0
0.0
0.0
3.5
3.5
2.0
0.0
0.0
32.0
0.0
0.0
0.0
0.0
23.0
14.5
0.0
80.0
0.0
0.0
6.0
1.0
0.0
0.0
0.0
45.0
110.0
0.0
0.0
48.5
33.0
25.0
22.5
107.0
35.0
0.0
0.0
0.0
0.0
0.0
7.0
2.0
0.0
0.0
30.0
74.0
0.0
40.0
8.5
0.5
0.0
0.0
61.0
0.0
95.5
39.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
41.0
0.0
74.5
0.0
16.5
0.0
0.0
0.0
58.0
0.0
2.5
0.0
0.0
0.0
2.5
0.0
69.0
0.0
0.0
0.0
0.0
1.0
0.0
71.0
55.5
0.0
3.0
0.0
0.0
0.0
48.0
0.0
0.0
84.0
97.0
0.0
33.0
0.0
2.5
82.0
107.0
0.0
0.0
14.5
10.0
0.0
68.0
47.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
157.0
0.0
0.0
0.0
0.0
0.0
14.0
33.0
32.5
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
12.5
0.0
0.0
0.0
0.0
0.0
24.0
0.0
6.0
0.0
205.5
81.0
111.5
0.0
74.0
83.5
0.0
290.0
0.0
206.0
1

True

In [12]:
img = cv2.imread('d3d10597-e629-4f08-853b-75472ae0de06.bmp',0)
img = cv2.medianBlur(img,5)
th3 = cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY,11,2)
cv2.imwrite("ADAPTIVE_THRESH_GAUSSIAN Thresholding.bmp", th3) 

True

In [32]:
image = cv2.imread('Threshold Binary70.bmp',0)
# It's good practice to blur images as it removes noise
image = cv2.GaussianBlur(image, (3, 3), 0)

# Using adaptiveThreshold
thresh = cv2.adaptiveThreshold(image, 255, cv2.ADAPTIVE_THRESH_MEAN_C, 
                               cv2.THRESH_BINARY, 3, 5) 
cv2.imwrite("Adaptive Mean Thresholding.bmp", thresh) 
# cv2.waitKey(0) 

_, th2 = cv2.threshold(image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imwrite("Otsu's Thresholding.bmp", th2) 
# cv2.waitKey(0) 

# Otsu's thresholding after Gaussian filtering
blur = cv2.GaussianBlur(image, (5,5), 0)
_, th3 = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
cv2.imwrite("Guassian Otsu's Thresholding.bmp", th3) 

# th3 = cv.adaptiveThreshold(image,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv.THRESH_BINARY,11,2)
# cv2.waitKey(0) 

True

In [12]:
img = cv2.imread('Threshold Binary70.bmp',0)

size = np.size(img)
skel = np.zeros(img.shape,np.uint8)

ret,img = cv2.threshold(img,127,255,cv2.THRESH_BINARY_INV)
# cv2.imwrite('test.bmp', img)
# img = cv2.Canny(img, 300, 120)
element = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3))
done = False

while( not done):
    eroded = cv2.erode(img,element)
    temp = cv2.dilate(eroded,element)
    temp = cv2.subtract(img,temp)
    skel = cv2.bitwise_or(skel,temp)
    img = eroded.copy()

    zeros = size - cv2.countNonZero(img)
    if zeros==size:
        done = True

cv2.imwrite('skel.bmp', skel)
# cv2.imshow("skel",skel)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

True

In [8]:
import cv2
import numpy as np

img = cv2.imread('out1.bmp',0)
size = np.size(img)
skel = np.zeros(img.shape,np.uint8)

ret,img = cv2.threshold(img,127,255,0)
element = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3))
done = False

while( not done):
    eroded = cv2.erode(img,element)
    temp = cv2.dilate(eroded,element)
    temp = cv2.subtract(img,temp)
    skel = cv2.bitwise_or(skel,temp)
    img = eroded.copy()

    zeros = size - cv2.countNonZero(img)
    if zeros==size:
        done = True

cv2.imshow("skel",skel)
cv2.waitKey(0)
cv2.destroyAllWindows()